swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    delivery_addresses: ['keemal540@gmail.com']
    transport: smtp
    auth_mode: login
    port: 25
    host: 127.0.0.1:8000/
    username: kemaltestsymfony@gmail.com
    password: Testsymfony
